import type { Metadata } from 'next';
import './global.css';

import * as styles from './theme.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={styles.themeClass}>{children}</body>
    </html>
  );
}
